#!/usr/bin/env zsh
# === {{CMD}} every SLEEP max X or until MY CMD --ARGS
#

local +x origin="$@"

case "$(echo $@ | xargs echo -n)" in
  "every "*" max "*" or until "*)
    shift; local +x SLEEP="$1"
    shift; shift; local +x MAX="$1"
    shift; shift; shift; local +x CMD="$@"
    if [[ "$MAX" -lt 1 ]]; then
      echo "!!! Invalid max, $MAX, for: loop $origin" >&2
      exit 5
    fi
    local +x COUNT=0
    setopt local_options shwordsplit
    while [[ "$COUNT" -lt "$MAX" ]]; do
      echo -n "."
      COUNT="$((COUNT + 1))"
      $CMD && return 0 || :
      sleep $SLEEP
    done
    exit 5
    ;;

  *)
    echo "!!! Invalid command: $origin" >&2
    exit 1
    ;;
esac
